name: Deploy Client
on:
  push:
    paths:
      - 'src/client/**/*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
        #   - name: Set up Node.js
        #     uses: actions/setup-node@v4
        #     with:
        #       node-version: '20'
        #   - name: Install dependencies
        #     run: npm install
        #   - name: Build
        #     run: npm run build
          - name: Deploy
            run: |
              echo "Deploying to client"
              # deploy to client